ear1grey/structured-start-tab

app/js/index.js, app/style/icons.css, manifest.json
addresses #45, it works for me 8-)
probably also needs the following:
=> use favicons

app/js/defaults.mjs, app/js/index.js, app/js/options.mjs, app/style/index.css
=> Dynamic Flex

src/style/options.css, src/style/toast.css
=> Make options page non-resizable

src/js/tooltip.ts
We propose this solution: We have added a condition that prevents the tooltip from leaving the screen. 
Fixes #101
=> Issue 101 (Tooltip Alignment)

_locales/en/messages.json, _locales/fr/messages.json, src/js/better-range/index.css, src/js/better-range/index.ts, src/js/color-switch/index.css, src/js/color-switch/index.ts, src/js/index.ts
Fixes #64 
We added a web component that combines a range and a numeric input.
Co-authored-by: @YassineSMR
=> issue64 : Better Range Component

_locales/en/messages.json, _locales/fr/messages.json, src/options.html, src/style/options.css
Add a return button in options
Fixes #98
Co-authored-by: @YassineSMR
=> Return button on options : issue 98

_locales/en/messages.json, _locales/fr/messages.json, manifest.json, src/js/background.ts, src/js/index.ts
We have added a top sites panel.
It is opened with the right-click menu.
Fix Issue #117 
=> Top sites panel - Issue117

src/js/defaults.ts, src/js/index.ts, src/js/options.ts
We have migrated the data to localStorage. 
We think that the option code can surely be improved. 
We don't know if continuing to use promises is a good thing. If it is no longer useful we can surely improve the code.
Co-authored: @toto101230 
Fix #83
=> Migrate to localStorage - Issue83

src/js/options.ts
Fixes #127
The promises now always resolve.
=> Starting Bug With localStorage

_locales/en/messages.json, _locales/fr/messages.json, src/js/options.ts, src/options.html
Fixes #115
We've added a reset button. We ask the user to make a backup before reset if they want.
=> A reset Button - Issue 115

_locales/en/messages.json, _locales/fr/messages.json, src/js/background.ts, src/js/index.ts
We can now display bookmarks panels by the right-click menu
Fixes #116
=> Bookmark Import Panel - Issue 116

_locales/en/messages.json, _locales/fr/messages.json, src/js/background.ts
We have set up a notification that pops up when users update the extension asking if they want to bring their old configuration.
Fix #113 
Co-authored-by: @YassineSMR
=> One-time migration path Issue #113

autobuild.js, manifest.json, package-lock.json, package.json, src/js/index.ts, src/js/version.js
We took the version of index.ts and sync it in other files
Fixes #96
=> Automate build process to change version - Issue 96 

_locales/en/messages.json, _locales/fr/messages.json, src/js/background.ts, src/js/index.ts
We've mirrored the sidebar to the context menu.
Fix #75 
=> Mirroring the sidebar to the context menu - Issue75

src/js/index.ts, src/js/toast.ts
isDupe() now only check if the last toast is the same as the one we want to display.
Fixes #87
=> New duplicate toasts should not be ignored. - Issue 87

_locales/en/messages.json, _locales/fr/messages.json, manifest.json, src/js/background.ts, src/js/defaults.ts, src/js/icalparse.ts, src/js/index.ts, src/js/options.ts, src/options.html
Fix #119 
We've added a panel that display an agenda.
The user need to put an ICS link in the options page. 
They can also choose the number of events to display.
The panel can be toggled from the context menu.
Co-authored : @toto101230
=> Agenda Panel - issue119

src/js/index.ts
We fixed the bug and we will now create issue for the enhancement
Fixes #147
=> Panel & Link data not saving after drag & drop - Issue 147

_locales/en/messages.json, _locales/fr/messages.json, src/js/index.ts, src/js/lib/icalparse.ts, src/js/lib/options.ts, src/js/lib/tooltip.ts, src/js/lib/types.ts, src/js/options-page.ts
We've done all the task except the link to the event. 
We searched how to do it from the .ics but we've found nothing.
Fix #154 
=> Small agenda improvements - Issue154

manifest.json, package.json, src/background.html, src/js/background.ts, src/js/index.ts, src/js/lib/icalparse.ts, src/js/lib/options.ts, src/js/lib/types.ts
We have implemented an update of the agenda in background using an alarm.
Fix : #152 
Co-authored: @YassineSMR 
We think the merge will be easier if this one is done after #155
=> Background load and update agenda : issue 152

src/js/index.ts, src/js/lib/icalparse.ts
If the event is today we display the time.
Else we display +dayDiff
Fixes #156
=> Agenda Terminology - Issue 156

_locales/en/messages.json, _locales/fr/messages.json, src/index.html, src/js/background.ts, src/js/index.ts, src/js/lib/icalparse.ts, src/js/lib/options.ts, src/js/lib/types.ts, src/js/options-page.ts
We've added multiple agenda.
The url is now in shift click editing page.
Co-authored: @toto101230 
The next step is to make this for all the other panels.
=> Multiple Agenda - Issue 160

_locales/en/messages.json, _locales/fr/messages.json, src/index.html, src/js/index.ts, src/style/index.css
We added a checkbox to turn off flex-wrap.
Fixes #149
=> Wrapping Panels - Issue 149

src/js/index.ts, src/js/lib/util.ts
The panel is now added before the panel which the mouse is located.
Fix #163 
=> Add where mouse is - Issue163

src/js/index.ts, src/style/index.css
Fixes #169
Co-authored-by: @YassineSMR
=> Flash of side bar : issue 169

src/js/background.js, src/js/components/agenda-item/index.css, src/js/components/agenda-item/index.js, src/js/index.js
The `agenda-item` component is now visible and it has been refactored so that it can now listen for changes in the attributes
=> Fix agenda component

manifest.json, package.json, src/js/background.js, src/test.html
=> remove usage of app folder

src/js/components/agenda-item/index.js, src/js/index.js, src/js/lib/icalparse.js
A change to put the right data in the agenda component, and a change so that times on the hour show right.
=> Agenda Tweak

src/js/components/panel/index.css, src/js/components/panel/index.js, src/js/lib/icalparse.js
=> Show full agenda item summary

package.json, src/index.html, update-manifest-version.js
=> Set beta properties

.gitignore, README.md, _locales/en/messages.json, src/index.html, src/js/index.js, src/js/lib/util.js, src/js/options-page.js, src/style/index.css, update-manifest-version.js
=> Add feedback button

src/background.html, src/js/background.js, src/js/index.js, src/js/services/agenda.service.js, src/js/services/cloud.service.js
Due to `background.js` being called from `index.js`, a new background listener was created every time a page was opened.
The functions required have been moved to a separate file to prevent this.
=> Multiple events triggered

_locales/en/messages.json, _locales/fr/messages.json, src/index.html
Complete translations for new elements.
=> Internationalisation

_locales/en/messages.json, _locales/fr/messages.json, src/js/components/panel/index.css, src/js/components/panel/index.js, src/js/index.js, src/js/lib/options.js, src/js/lib/util.js, src/js/services/parser.service.js, src/pages/options/index.js, src/style/index.css
=> Empty element name

_locales/en/messages.json, _locales/fr/messages.json, src/js/components/edit-window/index.css, src/js/components/panel/index.js, src/js/index.js, src/js/lib/util.js, src/js/services/drag.service.js, src/js/services/edit.service.js, src/js/services/parser.service.js, src/js/services/sync.service.js, src/js/services/sync/firebase.service.js, src/js/services/sync/simpleSstStorage.service.js
Allow users to subscribe to another user's panel.
Users must be on the same storage type/server.
=> Subscription panels

_locales/en/messages.json, _locales/fr/messages.json, src/js/components/edit-window/index.css, src/js/components/edit-window/index.html, src/js/components/edit-window/index.js, src/js/components/panel/index.css, src/js/components/panel/index.js, src/js/index.js, src/js/lib/util.js, src/js/services/agenda.service.js, src/js/services/edit.service.js, src/js/services/parser.service.js, src/js/services/sync.service.js, src/style/animations.css, src/style/index.css
- When editing a link or a panel, now the dialog shows a preview of the element
- Link icons can now be hidden
=> Edit elements preview
